<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="PseTest.http" />
    <Compile Include="Endpoints\Rce\RceReader.fs" />
    <Content Include="Endpoints\Rce\Rce.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup />

  <ItemGroup>
    <PackageReference Include="FSharp.Data" Version="6.4.1" />
  </ItemGroup>

</Project>
